# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.4
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: false
classname: HexGuide
default_branch: main
description: Hex Guide addon for Hex Casting
display_name: Hex Guide
github_repo: HexGuide
github_user: xm1221
homepage_url: https://xm1221.github.io/HexGuide
java_package: cn.xm1221.HexGuide
kotlin_package: cn.xm1221.HexGuide
mappings_name: Mojmap
minecraft_version_in_mod_version: false
mit_license: true
mod_version: 0.0,1
modid: hexguide
sources_url: https://github.com/xm1221/HexGuide
